---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: deps
    image: docker.io/golang:1.21
    commands:
      - make deps
    volumes:
      - name: godeps
        path: /go

  - name: generate
    image: docker.io/golang:1.21
    commands:
      - make generate
    volumes:
      - name: godeps
        path: /go

  - name: lint
    image: docker.io/golang:1.21
    commands:
      - make lint
    volumes:
      - name: godeps
        path: /go

  - name: test
    image: docker.io/golang:1.21
    commands:
      - make test
    volumes:
      - name: godeps
        path: /go

volumes:
  - name: godeps
    temp: {}

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: generate
    image: docker.io/golang:1.21
    commands:
      - make generate
    volumes:
      - name: godeps
        path: /go

  - name: build
    image: docker.io/golang:1.21
    commands:
      - make build
    volumes:
      - name: godeps
        path: /go

  - name: executable
    image: docker.io/golang:1.21
    commands:
      - dist/telegraf-hcloud --help

  - name: changelog
    image: quay.io/thegeeklab/git-chglog
    commands:
      - git fetch -tq
      - git-chglog --no-color --no-emoji ${DRONE_TAG:---next-tag unreleased unreleased}
      - git-chglog --no-color --no-emoji -o CHANGELOG.md ${DRONE_TAG:---next-tag unreleased unreleased}

  - name: release
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      note: CHANGELOG.md
      overwrite: true
      title: ${DRONE_TAG}
    when:
      ref:
        - refs/tags/**

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**

depends_on:
  - test

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
  - name: notify
    image: docker.io/plugins/slack
    settings:
      channel:
        from_secret: rocketchat_chat_channel
      webhook:
        from_secret: rocketchat_chat_webhook
    when:
      status:
        - failure

trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
  status:
    - success
    - failure

depends_on:
  - build

...
